# Generated by Django 6.0.4 on 2026-04-19 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("mtn_momo", "MTN MoMo"),
                            ("moov_money", "Moov Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction Mobile Money",
                "verbose_name_plural": "Transactions Mobile Money",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["backend", "status"],
                        name="django_mobi_backend_e67fa2_idx",
                    ),
                    models.Index(
                        fields=["phone", "created_at"],
                        name="django_mobi_phone_9f2dee_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("backend", models.CharField(max_length=20)),
                ("payload", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="django_mobile_money.mobiletransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
